buildVariable: false
sources:
  - FONTLAB_UFO_FILES/LondrinaSolid-Black.ufo
  - FONTLAB_UFO_FILES/LondrinaSolid-Light.ufo
  - FONTLAB_UFO_FILES/LondrinaSolid-Regular.ufo
  - FONTLAB_UFO_FILES/LondrinaSolid-Thin.ufo
