sources:
  - IBM-Plex-Mono/sources/masters/IBM Plex Mono Roman.designspace
  - IBM-Plex-Mono/sources/masters/IBM Plex Mono Italic.designspace
familyName: IBM Plex Mono
buildStatic: true
buildOTF: false
