sources:
  - "Sources/Cambay Regular/Cambay Devanagari-Regular.ufo"
  - "Sources/Cambay Oblique/Cambay Devanagari-Oblique.ufo"
  - "Sources/Cambay Bold/Cambay Devanagari-Bold.ufo"
  - "Sources/Cambay Bold Oblique/Cambay Devanagari-Bold Oblique.ufo"
buildVariable: false
