# Check to_sandbox.txt and to_production.txt do not contain typos
name: Continuous Test

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: ['**']

jobs:
  test_server_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Check to_sandbox.txt and to_production.txt do not contain typos
    - name: Install gftools
      run: pip install gftools[qa]
    - name: Lint server files
      run: |
        gftools push-status . --lint
        gftools font-tags lint .

  check_knowledge_graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Check Knowledge link graph
    - name: Install dependencies
      run: pip install absl-py mistune gftools
    - name: Check Knowledge graph
      run: python3 .github/workflows/knowledge_graph.py
